baseURL = "https://hi-breathelab.id/"
defaultContentLanguage = "en"
title = "Breathe Laboratory"

[params]
  description = "Biomedical Engineering Research Lab - DTETI FT UGM"
  subtitle = "Department of Electrical Engineering and Information Engineering UGM"
  contactEmail = "ridwan.wicaksono@ugm.ac.id"
  address = """Breathe Laboratory
Departemen Teknik Elektro dan Teknologi Informasi (DTETI)
Fakultas Teknik, Universitas Gadjah Mada
Jl. Grafika No. 2, Yogyakarta 55281"""
  mapEmbed = "https://www.google.com/maps?q=Fakultas+Teknik+Universitas+Gadjah+Mada&output=embed"

[languages]
  [languages.en]
    locale = "en-US"

[menus]
  [[menus.main]]
    name = "Research +"
    pageRef = "/research/"
    weight = 1
  [[menus.main]]
    name = "Publications +"
    pageRef = "/publication/"
    weight = 2
  [[menus.main]]
    name = "Team +"
    pageRef = "/team/"
    weight = 3
  [[menus.main]]
    name = "About +"
    pageRef = "/about/"
    weight = 4
  [[menus.main]]
    name = "Contact +"
    pageRef = "/contact/"
    weight = 5

  [[menus.footer]]
    name = "Research"
    pageRef = "/research/"
    weight = 1
  [[menus.footer]]
    name = "Publications"
    pageRef = "/publication/"
    weight = 2
  [[menus.footer]]
    name = "Team"
    pageRef = "/team/"
    weight = 3
  [[menus.footer]]
    name = "About"
    pageRef = "/about/"
    weight = 4
  [[menus.footer]]
    name = "Contact"
    pageRef = "/contact/"
    weight = 5

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
